spring:
  elasticsearch:
    rest:
      uris:
        - http://47.99.89.160:9220
      username:
      password:

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    max-connections: 20000