spring:
  elasticsearch:
    rest:
      uris:
        - http://34.96.251.173:9200
      username:
      password:

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    max-connections: 20000